---
# Yandex Cloud settings
yc_folder_id: "{{ lookup('env', 'YC_FOLDER_ID') }}"
yc_subnet_name: "{{ lookup('env', 'YC_SUBNET_NAME') }}"
yc_service_account_key: "{{ lookup('env', 'YC_SERVICE_ACCOUNT_KEY') | default(omit) }}"

# VM configuration
vm_zone: ru-central1-b
vm_image_family: ubuntu-2204-lts
vm_ssh_key_path: "{{ lookup('env', 'HOME') }}/.ssh/aleksey.pub"
vm_ssh_private_key: "{{ lookup('env', 'HOME') }}/.ssh/aleksey"
vm_default_user: yc-user
vm_platform_id: standard-v3
vm_cores: 2
vm_memory: 4
vm_core_fraction: 20
vm_disk_size: 20
vm_disk_type: network-hdd
vm_assign_public_ip: true
vm_preemptible: true
