---
namespace: aleksey_dubrovin
name: yc_obs_toolkit
version: 1.0.0
readme: README.md
authors:
  - Aleksey Dubrovin <aleksey.vladch@yandex.ru>
description: >
  Ansible collection for deploying observability stack
  on Yandex Cloud with EDA, ADK, and AEE support.
license:
  - GPL-3.0-or-later
tags:
  - yandexcloud
  - observability
  - eda
  - adk
  - aee
  - netology
repository: https://github.com/aleksey-dubrovin/yc-obs-toolkit
documentation: https://github.com/aleksey-dubrovin/yc-obs-toolkit
homepage: https://github.com/aleksey-dubrovin/yc-obs-toolkit
issues: https://github.com/aleksey-dubrovin/yc-obs-toolkit/issues