---
roles:
  - name: vector
    src: https://github.com/aleksey-dubrovin/vector-role.git
    version: main

  - name: lighthouse
    src: https://github.com/aleksey-dubrovin/lighthouse-role.git
    version: main

  - name: clickhouse
    src: https://github.com/AlexeySetevoi/ansible-clickhouse.git
    version: "1.13"