---
- name: Monitor file and notify MAX
  hosts: eda_test
  sources:
    - ansible.eda.file:
        paths:
          - /tmp/eda_monitor_test.txt
        event_type: "modify"
        recursive: false
        delay: 1
  rules:
    - name: File was modified - notify MAX
      condition: event.event_type == "modify"
      action:
        run_playbook:
          name: playbooks/notify_max.yml
          vars:
            event: "{{ event }}"